// <auto-generated />
using System;
using GreenYieldSolutions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenYieldSolutions.Migrations.BookFieldVisitDb
{
    [DbContext(typeof(BookFieldVisitDbContext))]
    partial class BookFieldVisitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GreenYieldSolutions.Models.FieldVisitRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CropType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FarmAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FarmerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeletedByAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("FieldVisitRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
